import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { BarChart3, ClipboardList, Flame, LogOut, MenuSquare, Settings, Users } from "lucide-react";
import { api, clearSession, hasSession, login } from "./api";
import "./styles.css";

type Page = "dashboard" | "orders" | "menu" | "customers" | "settings";
type Dashboard = { orders:number; customers:number; menuItems:number; pending:number; completedRevenue:number };
type Order = { id:string; orderNumber:string; status:string; fulfillment:string; total:string|number; createdAt:string; user:{name:string;email:string;phone?:string}; items:Array<{id:string;name:string;quantity:number}> };
type Category = { id:string; name:string };
type MenuItem = { id:string; name:string;description:string;price:string|number;imageUrl:string;tag?:string;allergens?:string;extraName?:string;extraPrice:string|number;isAvailable:boolean;isFeatured:boolean;categoryId:string;category:Category };
type Customer = { id:string;name:string;email:string;phone?:string;isActive:boolean;createdAt:string;_count:{orders:number} };
type RestaurantSettings = { restaurantName:string;phone?:string;address?:string;deliveryFee:string|number;minimumOrder:string|number;acceptingOrders:boolean };

const money = (n:number|string) => `R${Number(n).toFixed(2)}`;
function Login({onDone}:{onDone:()=>void}) {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  return <main className="login"><section className="loginCard"><div className="brandMark"><Flame size={24}/></div><p className="eyebrow">EMBER KITCHEN</p><h1>Admin sign in</h1><p className="muted">Manage orders, the live menu, customers and restaurant settings.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError("");try{await login(email,password);onDone();}catch(e){setError(e instanceof Error?e.message:"Login failed");}finally{setBusy(false);}}}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form></section></main>
}
function Shell() {
  const [page,setPage]=useState<Page>("dashboard"); const [version,setVersion]=useState(0);
  const nav:Array<[Page,string,React.ReactNode]>=[["dashboard","Overview",<BarChart3/>],["orders","Orders",<ClipboardList/>],["menu","Menu",<MenuSquare/>],["customers","Customers",<Users/>],["settings","Settings",<Settings/>]];
  return <div className="shell"><aside><div className="sideBrand"><span><Flame/></span><b>ember kitchen</b></div><nav>{nav.map(([id,label,icon])=><button key={id} className={page===id?"active":""} onClick={()=>setPage(id)}>{icon}{label}</button>)}</nav><button className="logout" onClick={async()=>{try{await api("/auth/logout",{method:"POST"});}catch{}clearSession();location.reload();}}><LogOut/>Sign out</button></aside><main className="main"><header><div><p className="eyebrow">RESTAURANT OPERATIONS</p><h1>{nav.find(n=>n[0]===page)?.[1]}</h1></div><button className="secondary" onClick={()=>setVersion(v=>v+1)}>Refresh</button></header>{page==="dashboard"&&<DashboardPage version={version}/>} {page==="orders"&&<OrdersPage version={version}/>} {page==="menu"&&<MenuPage version={version}/>} {page==="customers"&&<CustomersPage version={version}/>} {page==="settings"&&<SettingsPage version={version}/>}</main></div>
}
function DashboardPage({version}:{version:number}) { const [d,setD]=useState<Dashboard>(); useEffect(()=>{api<Dashboard>("/admin/dashboard").then(setD)},[version]); if(!d)return <p>Loading…</p>; const cards=[["Total orders",d.orders],["Open orders",d.pending],["Customers",d.customers],["Menu items",d.menuItems],["Completed revenue",money(d.completedRevenue)]]; return <div className="cards">{cards.map(c=><article key={String(c[0])}><span>{c[0]}</span><strong>{c[1]}</strong></article>)}</div> }
function OrdersPage({version}:{version:number}) { const [rows,setRows]=useState<Order[]>([]); const load=()=>api<Order[]>("/admin/orders").then(setRows); useEffect(()=>{load()},[version]); const statuses=["PENDING","CONFIRMED","PREPARING","READY","OUT_FOR_DELIVERY","COMPLETED","CANCELLED"]; return <section className="panel"><div className="tableWrap"><table><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Fulfilment</th><th>Total</th><th>Status</th></tr></thead><tbody>{rows.map(o=><tr key={o.id}><td><b>{o.orderNumber}</b><small>{new Date(o.createdAt).toLocaleString()}</small></td><td>{o.user.name}<small>{o.user.email}</small></td><td>{o.items.map(i=>`${i.quantity}× ${i.name}`).join(", ")}</td><td>{o.fulfillment.replaceAll("_"," ")}</td><td>{money(o.total)}</td><td><select value={o.status} onChange={async e=>{await api(`/admin/orders/${o.id}/status`,{method:"PATCH",body:JSON.stringify({status:e.target.value})});load();}}>{statuses.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></td></tr>)}</tbody></table></div></section> }
function MenuPage({version}:{version:number}) { const [items,setItems]=useState<MenuItem[]>([]); const [cats,setCats]=useState<Category[]>([]); const [open,setOpen]=useState(false); const blank={name:"",description:"",price:0,imageUrl:"",categoryId:"",tag:"",allergens:"",extraName:"",extraPrice:0,isAvailable:true,isFeatured:false}; const [form,setForm]=useState(blank); const load=()=>Promise.all([api<MenuItem[]>("/admin/menu"),api<Category[]>("/admin/categories")]).then(([a,b])=>{setItems(a);setCats(b);}); useEffect(()=>{load()},[version]); return <><div className="actions"><button onClick={()=>setOpen(!open)}>Add menu item</button></div>{open&&<form className="editor" onSubmit={async e=>{e.preventDefault();await api("/admin/menu",{method:"POST",body:JSON.stringify({...form,price:Number(form.price),extraPrice:Number(form.extraPrice)})});setForm(blank);setOpen(false);load();}}><input placeholder="Dish name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input placeholder="Price" type="number" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})} required/><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})} required><option value="">Category</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Image URL" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})} required/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/><input placeholder="Tag" value={form.tag} onChange={e=>setForm({...form,tag:e.target.value})}/><input placeholder="Allergens" value={form.allergens} onChange={e=>setForm({...form,allergens:e.target.value})}/><input placeholder="Optional extra name" value={form.extraName} onChange={e=>setForm({...form,extraName:e.target.value})}/><input placeholder="Extra price" type="number" value={form.extraPrice} onChange={e=>setForm({...form,extraPrice:Number(e.target.value)})}/><button>Save item</button></form>}<div className="menuGrid">{items.map(i=><article className="menuCard"><img src={i.imageUrl}/><div><small>{i.category.name}</small><h3>{i.name}</h3><p>{money(i.price)}</p><label className="toggle"><input type="checkbox" checked={i.isAvailable} onChange={async e=>{await api(`/admin/menu/${i.id}`,{method:"PATCH",body:JSON.stringify({isAvailable:e.target.checked})});load();}}/> Available</label><button className="danger" onClick={async()=>{if(confirm(`Delete ${i.name}?`)){await api(`/admin/menu/${i.id}`,{method:"DELETE"});load();}}}>Delete</button></div></article>)}</div></> }
function CustomersPage({version}:{version:number}) { const [rows,setRows]=useState<Customer[]>([]); useEffect(()=>{api<Customer[]>("/admin/customers").then(setRows)},[version]); return <section className="panel"><div className="tableWrap"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Orders</th><th>Joined</th></tr></thead><tbody>{rows.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.email}</td><td>{c.phone||"—"}</td><td>{c._count.orders}</td><td>{new Date(c.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></section> }
function SettingsPage({version}:{version:number}) { const [s,setS]=useState<RestaurantSettings>(); const [saved,setSaved]=useState(""); useEffect(()=>{api<RestaurantSettings>("/admin/settings").then(setS)},[version]); if(!s)return <p>Loading…</p>; return <form className="settings panel" onSubmit={async e=>{e.preventDefault();const next=await api<RestaurantSettings>("/admin/settings",{method:"PATCH",body:JSON.stringify({...s,deliveryFee:Number(s.deliveryFee),minimumOrder:Number(s.minimumOrder)})});setS(next);setSaved("Settings saved");}}><label>Restaurant name<input value={s.restaurantName} onChange={e=>setS({...s,restaurantName:e.target.value})}/></label><label>Phone<input value={s.phone||""} onChange={e=>setS({...s,phone:e.target.value})}/></label><label>Collection address<input value={s.address||""} onChange={e=>setS({...s,address:e.target.value})}/></label><label>Delivery fee<input type="number" value={Number(s.deliveryFee)} onChange={e=>setS({...s,deliveryFee:Number(e.target.value)})}/></label><label>Minimum order<input type="number" value={Number(s.minimumOrder)} onChange={e=>setS({...s,minimumOrder:Number(e.target.value)})}/></label><label className="toggle"><input type="checkbox" checked={s.acceptingOrders} onChange={e=>setS({...s,acceptingOrders:e.target.checked})}/> Accepting orders</label>{saved&&<p className="success">{saved}</p>}<button>Save settings</button></form> }
function App(){ const [authed,setAuthed]=useState(hasSession()); return authed?<Shell/>:<Login onDone={()=>setAuthed(true)}/> }
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
